name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history and branches
          filter: tree:0

      - name: Set SHAs
        uses: nrwl/nx-set-shas@v4
        
      - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"
        
      - name: Enforce All Conformance Rules
        run: npx nx-cloud record -- nx conformance:check

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npx nx affected -t lint,test,build,e2e-ci --parallel=3
